apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: soup-postgres-quarkus-blast
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: soup-postgres-quarkus-blast
    app.kubernetes.io/part-of: quarkus-blast
  name: soup-postgres-quarkus-blagry1
spec:
  port:
    targetPort: 5432
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: soup-postgres-quarkus-blast
    weight: 100
status: {}
